table(X2023_STB_survey $Gender)
ECN <- table(X2023_STB_survey $GendeR)
prop.table(ECN)
table(X2023_STB_survey $Gender, X2023_STB_survey $Grade)
barplot(table(X2023_STB_survey $Gender))
entry <- table(X2023_STB_survey $Gender,X2023_STB_survey $Grade)
barplot(entry, legend = TRUE)
bie(table(X2023_STB_survey $Grade)
pie(table(X2023_STB_survey $Grade))
barplot(table(X2023_STB_survey $Nationality))
barplot(table(X2023_STB_survey $`residential area`))
barplot(table(X2023_STB_survey $Gender,X2023_STB_survey $Grade)
barplot(table(X2023_STB_survey $Gender))
hist $Age,col = terrain.colors(12))        
